extends SceneTree

## Deterministic native/UI smoke for the first local-library release.
##
## The source ROM is generated by the repository's make-test-rom.py helper and
## supplied through RETROLIFE_TEST_ROM (or the repository .cache default). It
## is never committed or copied into the Godot project. The smoke uses an
## isolated managed library and verifies import, view, details, core startup,
## video delivery, pause/resume, and clean stop.

const SMOKE_SCHEMA_VERSION := 1
const MAX_START_FRAMES := 180
const SNES_INPUT_ACTIONS: Array[String] = [
    "up", "down", "left", "right", "south", "east", "west", "north",
    "left_shoulder", "right_shoulder", "start", "select",
]

var _backend: Node
var _gameplay: Control
var _smoke_root: String
var _source_rom: String
var _core_path: String


func _init() -> void:
    call_deferred("_run")


func _run() -> void:
    var failure := await _execute()
    # Let the audio server release the generator playback after the native
    # stop event before the presentation node is freed.
    await process_frame
    await process_frame
    _cleanup_backend()
    if not _smoke_root.is_empty():
        _remove_tree(_smoke_root)
    if failure.is_empty():
        print("RetroLife local-library smoke passed")
        quit(0)
    else:
        push_error("RetroLife local-library smoke failed: %s" % failure)
        quit(1)


func _execute() -> String:
    _source_rom = OS.get_environment("RETROLIFE_TEST_ROM")
    if _source_rom.is_empty():
        _source_rom = ProjectSettings.globalize_path("res://../../.cache/test.sfc")
    _core_path = OS.get_environment("RETROLIFE_CORE_PATH")
    if _core_path.is_empty():
        var core_name := "bsnes-jg_libretro.dylib" if OS.get_name() == "macOS" else "bsnes-jg_libretro.so"
        _core_path = ProjectSettings.globalize_path("res://bin/" + core_name)
    if not FileAccess.file_exists(_source_rom):
        return "test ROM is missing; run scripts/make-test-rom.py first"
    if not FileAccess.file_exists(_core_path):
        return "the development libretro core is missing; run scripts/build-core.sh first"

    var smoke_parent := OS.get_environment("RETROLIFE_SMOKE_ROOT")
    if smoke_parent.is_empty():
        smoke_parent = ProjectSettings.globalize_path("res://../../.cache/godot-ui-smoke")
    # Never recursively delete a caller-owned root. Each run gets a new child,
    # and only that child is removed after the smoke finishes.
    _smoke_root = smoke_parent.path_join("run-%s-%s" % [Time.get_ticks_usec(), OS.get_process_id()])
    var directory_error := DirAccess.make_dir_recursive_absolute(_smoke_root)
    if directory_error != OK:
        return "could not create the isolated smoke directory"
    var library_root := _smoke_root.path_join("library")
    var save_root := _smoke_root.path_join("saves")

    _backend = ClassDB.instantiate("RetroLifeBackend") as Node
    if _backend == null:
        return "RetroLifeBackend could not be instantiated"

    var configured := _decode(_backend.call(
        "configure_paths_json",
        library_root,
        save_root,
        _core_path
    ))
    if not bool(configured.get("ok", false)):
        return str(configured.get("error", "path configuration failed"))

    var imported := _decode(_backend.call("library_import_json", _source_rom))
    if not bool(imported.get("ok", false)):
        return str(imported.get("error", "local import failed"))
    var imported_data: Dictionary = imported.get("data", {})
    var game_id := str(imported_data.get("id", ""))
    if game_id.is_empty():
        return "local import did not return a game identity"

    var view := _decode(_backend.call("library_view_json", "", "", 0, 500))
    if not bool(view.get("ok", false)):
        return str(view.get("error", "local library view failed"))
    var view_data: Dictionary = view.get("data", {})
    var games: Array = view_data.get("games", [])
    if games.size() != 1 or str((games[0] as Dictionary).get("id", "")) != game_id:
        return "local library view did not contain the imported game"
    if not bool((games[0] as Dictionary).get("playable", false)):
        return "local library marked the generated SNES fixture as unplayable"

    var details := _decode(_backend.call("library_game_details_json", game_id))
    if not bool(details.get("ok", false)):
        return str(details.get("error", "local game details failed"))
    if str((details.get("data", {}) as Dictionary).get("id", "")) != game_id:
        return "local game details returned the wrong identity"

    var gameplay_script: Script = load("res://scripts/launch_integration.gd") as Script
    if gameplay_script == null:
        return "the gameplay presentation script could not be loaded"
    _gameplay = gameplay_script.new() as Control
    if _gameplay == null:
        return "the gameplay presentation could not be instantiated"
    root.add_child(_gameplay)
    _gameplay.call("configure", _backend, _gameplay)

    var started: Dictionary = _gameplay.call("start_game", game_id, "Smoke Fixture")
    if not bool(started.get("ok", false)):
        return str(started.get("error", "emulation did not start"))

    var running_failure := await _wait_for_status("running")
    if not running_failure.is_empty():
        _backend.call("stop_emulation_json")
        return running_failure
    var running_status := _decode(_backend.call("emulation_status_json"))
    var running_data: Dictionary = running_status.get("data", {})
    var expected_width := int(running_data.get("videoWidth", 0))
    var expected_height := int(running_data.get("videoHeight", 0))
    var expected_sample_rate := float(running_data.get("sampleRate", 0.0))
    var expected_fps := float(running_data.get("fps", 0.0))
    var expected_aspect := float(running_data.get("aspectRatio", 0.0))
    if expected_width <= 0 or expected_height <= 0 or expected_sample_rate <= 0.0 \
        or expected_fps <= 0.0 or expected_aspect <= 0.0:
        _backend.call("stop_emulation_json")
        return "the running session did not expose real video/audio metadata"

    var input_failure := _exercise_input_contract()
    if not input_failure.is_empty():
        _backend.call("stop_emulation_json")
        return input_failure

    var frame_node := _gameplay.get_node_or_null(
        "GameplayMargin/GameplayColumn/GameplayFramePanel/GameplayFrameAspect/GameplayFrame"
    ) as TextureRect
    var aspect_node := _gameplay.get_node_or_null(
        "GameplayMargin/GameplayColumn/GameplayFramePanel/GameplayFrameAspect"
    ) as AspectRatioContainer
    if frame_node == null or aspect_node == null:
        _backend.call("stop_emulation_json")
        return "the gameplay presentation did not build its frame container"

    for _index in range(MAX_START_FRAMES):
        await process_frame
        if frame_node.texture != null:
            break
    if frame_node.texture == null:
        _backend.call("stop_emulation_json")
        return "the gameplay presentation did not receive an ImageTexture"
    var texture := frame_node.texture as ImageTexture
    if texture == null or texture.get_width() <= 0 or texture.get_height() <= 0:
        _backend.call("stop_emulation_json")
        return "the gameplay presentation received an invalid ImageTexture"
    var frame_info := _decode(_backend.call("emulation_frame_info_json"))
    var frame_data: Dictionary = frame_info.get("data", {})
    var frame_width := int(frame_data.get("width", 0))
    var frame_height := int(frame_data.get("height", 0))
    if not bool(frame_info.get("ok", false)) or frame_width <= 0 or frame_height <= 0:
        _backend.call("stop_emulation_json")
        return "the bridge did not pair video bytes with frame metadata"
    if texture.get_width() != frame_width or texture.get_height() != frame_height:
        _backend.call("stop_emulation_json")
        return "the gameplay ImageTexture size does not match the frame metadata"
    if not is_equal_approx(aspect_node.ratio, float(frame_data.get("aspectRatio", 0.0))):
        _backend.call("stop_emulation_json")
        return "the gameplay aspect container did not use the core display ratio"

    var image := texture.get_image()
    if image == null or image.get_data().size() != frame_width * frame_height * 4:
        _backend.call("stop_emulation_json")
        return "the gameplay ImageTexture data does not match its frame metadata"
    if float(frame_data.get("sampleRate", 0.0)) <= 0.0 \
        or float(frame_data.get("fps", 0.0)) <= 0.0 \
        or float(frame_data.get("aspectRatio", 0.0)) <= 0.0:
        _backend.call("stop_emulation_json")
        return "the frame metadata did not include real audio/video timing"

    _gameplay.call("_toggle_pause")
    var pause_failure := await _wait_for_status("paused")
    if not pause_failure.is_empty():
        _backend.call("stop_emulation_json")
        return pause_failure
    _gameplay.call("_resume_game")
    var resume_failure := await _wait_for_status("running")
    if not resume_failure.is_empty():
        _backend.call("stop_emulation_json")
        return resume_failure
    _gameplay.call("_stop_session")
    var stop_failure := await _wait_for_stopped()
    if not stop_failure.is_empty():
        return stop_failure
    return ""


func _exercise_input_contract() -> String:
    for action in SNES_INPUT_ACTIONS:
        var pressed := _decode(_backend.call("set_emulation_input_json", action, true))
        if not bool(pressed.get("ok", false)):
            return "the bridge rejected SNES input '%s': %s" % [action, pressed.get("error", "unknown error")]
        var released := _decode(_backend.call("set_emulation_input_json", action, false))
        if not bool(released.get("ok", false)):
            return "the bridge could not release SNES input '%s': %s" % [action, released.get("error", "unknown error")]
    return ""


func _cleanup_backend() -> void:
    if is_instance_valid(_gameplay):
        _gameplay.free()
        _gameplay = null
    if not is_instance_valid(_backend):
        return
    _backend.call("stop_emulation_json")
    _backend.free()
    _backend = null


func _wait_for_stopped() -> String:
    return await _wait_for_status("stopped")


func _wait_for_status(expected: String) -> String:
    for _index in range(MAX_START_FRAMES):
        await process_frame
        var response := _decode(_backend.call("emulation_status_json"))
        if not bool(response.get("ok", false)):
            return str(response.get("error", "could not verify stop"))
        var data: Dictionary = response.get("data", {})
        var status := str(data.get("status", ""))
        if status == expected:
            return ""
        if status == "failed" and expected != "failed":
            return str(data.get("lastError", "the emulator failed while saving"))
    return "the emulator did not reach the expected status '%s' in time" % expected


func _decode(raw: Variant) -> Dictionary:
    var parsed: Variant = raw
    if raw is String or raw is StringName:
        parsed = JSON.parse_string(str(raw))
    if typeof(parsed) != TYPE_DICTIONARY:
        return {"schemaVersion": SMOKE_SCHEMA_VERSION, "ok": false, "error": "invalid JSON"}
    var response: Dictionary = parsed
    if int(response.get("schemaVersion", -1)) != SMOKE_SCHEMA_VERSION:
        return {"schemaVersion": SMOKE_SCHEMA_VERSION, "ok": false, "error": "unsupported schema"}
    return response


func _remove_tree(path: String) -> void:
    var directory := DirAccess.open(path)
    if directory == null:
        return
    directory.list_dir_begin()
    while true:
        var name := directory.get_next()
        if name.is_empty():
            break
        if name == "." or name == "..":
            continue
        var child := path.path_join(name)
        if directory.current_is_dir():
            _remove_tree(child)
        else:
            DirAccess.remove_absolute(child)
    directory.list_dir_end()
    DirAccess.remove_absolute(path)
